server:
  port: 8082
spring:
  application:
    name: notification-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/notification-service
  jpa:
    hibernate:
      ddl-auto: create-drop #todo change to validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # 100% запросов трассируются
  zipkin:
    enabled: true
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routeing-keys:
    internal-notification: internal.notification.routing-key
