spring:
  zipkin:
    base-url: http://zipkin:9411
  datasource:
    url: jdbc:postgresql://postgres:5432/notification-service
  rabbitmq:
    addresses: rabbitmq:5672

management:
  zipkin:
    enabled: true
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
