server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud-service
          uri: lb://fraud-service
          predicates:
            - Path=/api/v1/fraud-check/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    #    propagation:
    #      type: W3C
    enabled: true
    sampling:
      probability: 1.0 # 100% запросов трассируются
  zipkin:
    enabled: true
    tracing:
      endpoint: http://localhost:9411/api/v2/spans