apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-service
  labels:
    app: fraud-service
spec:
  replicas: 1
  template:
    metadata:
      name: fraud-service
      labels:
        app: fraud-service
    spec:
      containers:
        - name: fraud-service
          image: gontarenko/fraud-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      restartPolicy: Always
  selector:
    matchLabels:
      app: fraud-service
