spring:
  zipkin:
    base-url: http://zipkin:9411
  datasource:
    url: jdbc:postgresql://postgres:5432/fraud-service

management:
  zipkin:
    enabled: true
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
