spring:
  zipkin:
    base-url: http://zipkin:9411
  datasource:
    url: jdbc:postgresql://postgres:5432/fraud-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
    enabled: false

management:
  zipkin:
    enabled: true
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans