apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  template:
    metadata:
      name: notification-service
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: gontarenko/notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082 # todo проверить 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification-service
