spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
#    propagation:
#      type: W3C
    enabled: true
    sampling:
      probability: 1.0 # 100% запросов трассируются
  zipkin:
    enabled: true
    tracing:
      endpoint: http://localhost:9411/api/v2/spans